baseURL: "https://www.kairrin.net"
title: Kairrin.net
copyright: "© Édité avec ❤️ par [Kairrin](https://github.com/Kairrin-net/)"
paginate: 5
theme: [PaperMod]

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["posts", "accueil"]

minify:
  disableXML: true
  # minifyOutput: true

defaultContentLanguage: fr 
languages:
  fr:
    languageName: ":fr:"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Posts
          url: posts/
          weight: 10
        - name: Rechercher un tutoriel
          url: search/
          weight: 5
        - name: Tags
          url: tags/
          weight: 10
        - name: Accès aux exercices
          url: https://github.com/Kairrin-net/Kairrin-Exercices/

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Bienvenue sur Kairrin.net. Notre objectif est de proposer aux débutants des explications claires et détaillées sur les notions de base de l’informatique"
  author: Kairrin

  defaultTheme: auto
  # disableThemeToggle: true 
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
  comments: true
  images: ["https://raw.githubusercontent.com/Kairrin-net/Kairrin-Website/a52b148eae0d358baf002c75d79b73073d619ab5/assets/images/cover.svg"]

  homeInfoParams:
    Title: "Kairrin.Net"
    Content: >
      👋 Bienvenue sur **Kairrin.net**.

      - Notre objectif est de proposer aux débutants des explications claires et détaillées sur les notions de base de l'informatique

      - Le site **Kairrin.net** est une plateforme éducative basée sur le partage de connaissances, où chacun peut contribuer en proposant des tutoriels ou des améliorations.

  socialIcons:
    - name: rootme
      title: Profile Root-me
      url: "https://www.root-me.org/Kairrin"
    - name: Discord
      title: Rejoindre notre communauté
      url: "https://discord.gg/MsAScXtavf"
    - name: Github
      title: Accédez aux exercices
      url: "https://github.com/Kairrin-net/"

  buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags


  editPost:
    URL: "https://github.com/Kairrin-net/Kairrin-Website/tree/main/content"
    Text: "Partagez votre idée"
    appendFilePath: true 

  assets:
    disableHLJS: true
    favicon: "https://raw.githubusercontent.com/Kairrin-net/Kairrin-Website/refs/heads/main/assets/images/favicon.ico"
    favicon16x16: "https://raw.githubusercontent.com/Kairrin-net/Kairrin-Website/refs/heads/main/assets/images/favicon-16x16.png"
    favicon32x32: "https://raw.githubusercontent.com/Kairrin-net/Kairrin-Website/refs/heads/main/assets/images/favicon-32x32.png"
    apple_touch_icon: "https://raw.githubusercontent.com/Kairrin-net/Kairrin-Website/refs/heads/main/assets/images/apple-touch-icon.png"
    safari_pinned_tab: "https://raw.githubusercontent.com/Kairrin-net/Kairrin-Website/refs/heads/main/assets/images/favicon.ico"

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
