baseURL: "https://Kairrin.net/"
title: Kairrin.net
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Kairrin.net
  description: "Bienvenue sur mon Blog ! Je vous partage ici des tutoriels et des exercices pour mieux comprendre et aprehender l'informatique"
  keywords: [Blog, Portfolio, PaperMod]
  author: Kairrin
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: dark # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Accueil"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Kairrin
    subtitle: "Bienvenue sur mon blog ! Decouvrez ici des cours et des exercices pour mieux comprendre l'informatique"
    imageUrl: "https://i.kym-cdn.com/entries/icons/facebook/000/040/642/terrifiednootnoot.jpg"
    imageWidth: 200
    imageHeight: 200
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  # homeInfoParams:
  #   Title: "Kairrin.net"
  #   Content: Bienvenue sur mon blog ! Decouvrez ici des cours et des exercices pour mieux comprendre l'informatique

  socialIcons:
    - name: x
      url: "https://x.com/"
    - name: rootme
      url: "https://www.root-me.org/Kairrin"
    - name: Github
      url: "https://github.com/Kairrin-net"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/<path_to_repo>/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: presentation
      name: Qui suis-je
      url: /categories/
      weight: 10
    # - identifier: categories
    #   name: Catégories
    #   url: /categories/
    #   weight: 20
    # - identifier: search
    #   name: Chercher du contenu
    #   url: /categories/
    #   weight: 30
    # - identifier: github
    #   name: Accès aux exercices
    #   url: https://example.org
    #   weight: 40

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai